### ISSUE TITLE
License

### ISSUE THREAD

**Issue by almereyda** [phillmac/torrent-health-scraper#3]
As a follow up of #2 it would be optimal to assign a certain license to this repository, in so contributor's rights are explicit and protected right from the beginning.

My suggestions for this kind of software would primarily be:

- https://unlicense.org/
- http://www.wtfpl.net/

or any other from https://en.wikipedia.org/wiki/Public-domain-equivalent_license, which adds the Zero Clause BSD license to the list. If less freedom is required, we would still do good in applying at least one of:

- AGPL
- MIT
- Apache

to have fundamental agreements about how working together here is organised to be put into place.

**Comment by phillmac** [comment]
Until now it did have the MIT license, however I've just switched it to the Unlicense.
I'd have preferred the wtfpl except for the fact it has no limits on liability xD

**Comment by almereyda** [comment]
At first, I am sorry for having blindedly ignored the actual presence of the file. Sorry for having mixed up this repository with another.

And a little proud the additional information made you revisit your choice to spread love freely now ^W^.

WTFPL is a classic, and it's irony doesn't miss being an appropriate comment on the state of IP regulation these days.
